import datetime
import time


def simple_table(table_arr, config):
    table_str = ""
    for index, row in enumerate(table_arr):
        if index == 0 and config.simple_header:
            table_str += (f"||~ {'||~ '.join(map(str, row))}||\n")
        else:
            table_str += (f"||{'||'.join(map(str, row))}||\n")
    table_str += footnote(config)
    return table_str


def advanced_table(table_arr, config):
    table_str = '[[table  style="border-collapse:collapse;"]]\n'
    for index, row in enumerate(table_arr):
        row_str = "[[row]]\n"
        for cell in row:
            back_color = config.advanced_header_color if config.advanced_header and index == 0 \
                else config.advanced_background_color
            row_str += f'[[{"hcell" if config.advanced_header and index == 0 else "cell"} ' \
                       f'style="border: {config.advanced_border}; background-color: ' \
                       f'{back_color}"]]\n' \
                       f'{cell}\n' \
                       f'[[/{"hcell" if config.advanced_header and index == 0 else "cell"}]]\n'
        row_str += "[[/row]]\n"
        table_str += row_str
    table_str += "[[/table]]\n\n"
    table_str += footnote(config)
    return table_str


def footnote(config):
    return f"[!--\n" \
           f"Generated by {config.program_name} version {config.version} on {datetime.date.today()}" \
           f" at {time.strftime('%H:%M:%S')}\n" \
           f"--]\n"

